-- Script to configure Always Encrypted for sensitive columns
-- This provides client-side encryption for highly sensitive data

-- Step 1: Create Column Master Key (CMK) pointing to Azure Key Vault
-- Replace with actual Azure Key Vault URL
CREATE COLUMN MASTER KEY [CMK_TenantSensitiveData]
WITH (
    KEY_STORE_PROVIDER_NAME = 'AZURE_KEY_VAULT',
    KEY_PATH = 'https://your-keyvault.vault.azure.net/keys/TenantCMK/version'
);
GO

-- Step 2: Create Column Encryption Key (CEK) encrypted by the CMK
-- The encrypted value would be generated by the client application
-- This is a placeholder - actual implementation requires Azure Key Vault integration
CREATE COLUMN ENCRYPTION KEY [CEK_TenantSensitiveData]
WITH VALUES (
    COLUMN_MASTER_KEY = [CMK_TenantSensitiveData],
    ALGORITHM = 'RSA_OAEP',
    ENCRYPTED_VALUE = 0x... -- This would be the actual encrypted key from Azure Key Vault
);
GO

-- Step 3: Example of creating a table with encrypted columns
-- This demonstrates how to mark sensitive fields for encryption
CREATE TABLE PatientRecords (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    PatientName NVARCHAR(200) COLLATE Latin1_General_BIN2 
        ENCRYPTED WITH (
            COLUMN_ENCRYPTION_KEY = [CEK_TenantSensitiveData],
            ENCRYPTION_TYPE = DETERMINISTIC,
            ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
        ),
    SSN NVARCHAR(11) COLLATE Latin1_General_BIN2 
        ENCRYPTED WITH (
            COLUMN_ENCRYPTION_KEY = [CEK_TenantSensitiveData],
            ENCRYPTION_TYPE = DETERMINISTIC,
            ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
        ),
    MedicalHistory NVARCHAR(MAX) COLLATE Latin1_General_BIN2 
        ENCRYPTED WITH (
            COLUMN_ENCRYPTION_KEY = [CEK_TenantSensitiveData],
            ENCRYPTION_TYPE = RANDOMIZED,
            ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256'
        ),
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);
GO

-- Step 4: Verify encryption configuration
SELECT 
    cmk.name AS ColumnMasterKeyName,
    cmk.key_store_provider_name AS KeyStoreProvider,
    cmk.key_path AS KeyPath,
    cek.name AS ColumnEncryptionKeyName,
    cek.encryption_algorithm_name AS Algorithm
FROM sys.column_master_keys cmk
LEFT JOIN sys.column_encryption_key_values cekv ON cmk.column_master_key_id = cekv.column_master_key_id
LEFT JOIN sys.column_encryption_keys cek ON cekv.column_encryption_key_id = cek.column_encryption_key_id;
GO

-- Step 5: Verify column encryption
SELECT 
    t.name AS TableName,
    c.name AS ColumnName,
    c.encryption_type AS EncryptionType,
    CASE c.encryption_type
        WHEN 0 THEN 'Not Encrypted'
        WHEN 1 THEN 'Deterministic'
        WHEN 2 THEN 'Randomized'
    END AS EncryptionTypeDescription,
    cek.name AS ColumnEncryptionKeyName
FROM sys.columns c
INNER JOIN sys.tables t ON c.object_id = t.object_id
LEFT JOIN sys.column_encryption_keys cek ON c.column_encryption_key_id = cek.column_encryption_key_id
WHERE c.encryption_type > 0;
GO
