apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.platformSystem }}
  labels:
    name: {{ .Values.namespaces.platformSystem }}
    purpose: multi-tenant-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.gateway }}
  labels:
    name: {{ .Values.namespaces.gateway }}
    purpose: gateway
---
{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.observability }}
  labels:
    name: {{ .Values.namespaces.observability }}
    purpose: observability
{{- end }}
